apiVersion: v1
kind: ConfigMap
metadata:
  name: drift-detection-api-configmap
  namespace: core
data:
  LOG_LEVEL: "INFO"
  DRIFT_DETECTION_API_WORKERS: "1"
  POSTGRES_HOST: "127.0.0.1"
  POSTGRES_PORT: "5432"
  POSTGRES_POOL_MIN_SIZE: "1"
  POSTGRES_POOL_MAX_SIZE: "10"
  POSTGRES_POOL_TIMEOUT_S: "5"
  BASELINE_DATA_PATH: "/app/dataset/training_data.parquet"
