apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: drift-detection-api-secrets
  namespace: core
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: drift-detection-api-secrets
    template:
      data:
        POSTGRES_USER: "{{ .pg_user }}"
        POSTGRES_PASSWORD: "{{ .pg_password }}"
        POSTGRES_DB: "fraud-detection"
        CLOUD_SQL_INSTANCE: "project-57f7ef9a-6059-4068-ae7:us-central1:fraud-detection"
  data:
    - secretKey: pg_user
      remoteRef:
        key: fraud-pg-user
    - secretKey: pg_password
      remoteRef:
        key: fraud-pg-password
