apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-refresher-configmap
data:
  REDIS_HOST: "10.207.204.179"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_POOL_MAX_CONNECTIONS: "64"
  REDIS_POOL_TIMEOUT_S: "5"
  REDIS_FEATURE_CUTOFF_DAYS: "30"
  KAFKA_MAX_RECORDS: "100"
  KAFKA_TIMEOUT_MS: "1000"
  PREDICTIONS_TOPIC: "predictions"
  BOOTSTRAP_SERVERS: "bootstrap.fraud-detection.us-central1.managedkafka.project-8f21156c-3434-4d17-a8c.cloud.goog:9092"

