apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-detection-configmap
data:
  LOG_LEVEL: "INFO"
  FRAUD_DETECTION_API_WORKERS: "5"
  REDIS_HOST: "10.102.22.67"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_POOL_MAX_CONNECTIONS: "64"
  REDIS_POOL_TIMEOUT_S: "5"
  POSTGRES_HOST: "127.0.0.1"
  POSTGRES_PORT: "5432"
  POSTGRES_POOL_MIN_SIZE: "1"
  POSTGRES_POOL_MAX_SIZE: "10"
  POSTGRES_POOL_TIMEOUT_S: "5"
  KSERVE_URL: "http://fraud-detection.serving.svc.cluster.local/v2/models/fraud-detection/infer"
  KSERVE_TIMEOUT_S: "30"
  KSERVE_MAX_CONNECTIONS: "100"
  KSERVE_MAX_KEEPALIVE_CONNECTIONS: "100"
  MODEL_NAME: "fraud-detection"
  PREDICTIONS_TOPIC: "predictions"
  BOOTSTRAP_SERVERS: "fraud-detection-niemhoalongvu-8584.e.aivencloud.com:17550"
  KAFKA_SECURITY_PROTOCOL: "SSL"
  KAFKA_SSL_CAFILE: "/app/certs/ca.pem"
  KAFKA_SSL_CERTFILE: "/app/certs/service.cert"
  KAFKA_SSL_KEYFILE: "/app/certs/service.key"
  DECISION_THRESHOLD: "0.8"
  CARD_TRANSACTIONS_KEY: "card:transactions"
  CARD_AGGREGATE_KEY: "card:aggregate"
  CARD_DECLINES_KEY: "card:declines"
  USER_TRANSACTIONS_KEY: "user:transactions"
  USER_AGGREGATE_KEY: "user:aggregate"