apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: grafana-secrets
    template:
      data:
        GRAFANA_PG_HOST: "127.0.0.1"
        GF_PG_PORT: "5432"
        GF_PG_DB: "fraud-detection"
        GF_PG_USER: "{{ .pg_user }}"
        GF_PG_PASSWORD: "{{ .pg_password }}"
        CLOUD_SQL_INSTANCE: "project-57f7ef9a-6059-4068-ae7:us-central1:fraud-detection"
  data:
    - secretKey: pg_user
      remoteRef:
        key: fraud-pg-user
    - secretKey: pg_password
      remoteRef:
        key: fraud-pg-password
