apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: {{ .Values.namespace }}
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: {{ .Values.loki.httpPort }}
      grpc_listen_port: {{ .Values.loki.grpcPort }}

    common:
      instance_addr: 127.0.0.1
      path_prefix: /loki
      storage:
        gcs:
          bucket_name: {{ .Values.storage.gcsBucket }}
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: {{ .Values.config.schemaFrom }}
          store: tsdb
          object_store: gcs
          schema: v13
          index:
            prefix: index_
            period: 24h

    limits_config:
      allow_structured_metadata: true
      volume_enabled: true
      retention_period: {{ .Values.config.retentionPeriod }}

    compactor:
      retention_enabled: true
      delete_request_store: gcs

    ruler:
      alertmanager_url: {{ .Values.config.alertmanagerUrl }}
      storage:
        type: gcs
        gcs:
          bucket_name: {{ .Values.storage.rulerBucket }}
