apiVersion: v1
kind: Service
metadata:
  name: loki-headless
  namespace: {{ .Values.namespace }}
  labels:
    app: loki
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
  selector:
    app: loki
