apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: {{ .Values.namespace }}
  labels:
    app: loki
spec:
  replicas: {{ .Values.loki.replicas }}
  selector:
    matchLabels:
      app: loki
  serviceName: loki-headless
  template:
    metadata:
      labels:
        app: loki
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: loki
          image: {{ .Values.loki.image }}
          args:
            - -config.file=/etc/loki/loki.yaml
          ports:
            - name: http
              containerPort: {{ .Values.loki.httpPort }}
            - name: grpc
              containerPort: {{ .Values.loki.grpcPort }}
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: data
              mountPath: /loki
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 45
            periodSeconds: 30
          resources:
            {{- toYaml .Values.loki.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: data
          emptyDir: {}
