apiVersion: v2
name: transaction-writer
description: Helm chart for Transaction Writer deployment
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - fraud-detection
  - deployment
  - transaction-writer
