namespace: core

api:
  name: fraud-detection-api
  replicaCount: 1
  image:
    repository: us-central1-docker.pkg.dev/project-2a55a756-9eba-4a36-8c6/fraud-detection/fraud-detection-api
    tag: "latest"
    pullPolicy: Always
  port: 8000
  resources:
    requests:
      cpu: "250m"
      memory: "1Gi"
    limits:
      cpu: "1500m"
      memory: "2Gi"

serviceAccount:
  name: fraud-detection-api-sa
  gcpServiceAccount: "fraud-detection-api-sa@project-2a55a756-9eba-4a36-8c6.iam.gserviceaccount.com"

service:
  type: ClusterIP
  port: 80
  targetPort: http

ingress:
  enabled: true
  host: "fraud-detection-api.aide-production.136.114.159.18.sslip.io"
  ingressClassName: nginx
  rewriteTarget: "/"
  maxBodySize: "50m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilization: 70
  targetMemoryUtilization: 85
