namespace: core

featureRefresher:
  name: feature-refresher
  replicaCount: 1
  image:
    repository: us-central1-docker.pkg.dev/project-8f21156c-3434-4d17-a8c/fraud-detection/feature-refresher
    tag: "latest"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "250m"
      memory: "1Gi"
    limits:
      cpu: "1500m"
      memory: "2Gi"

serviceAccount:
  name: feature-refresher-sa
  gcpServiceAccount: "feature-refresher-sa@project-8f21156c-3434-4d17-a8c.iam.gserviceaccount.com"
